const express = require('express')
const registerController = require('../http/controllers/auth/register-controller')
const productController = require('../http/controllers/product-controller')
const cartController = require('../http/controllers/cart-controller')
const loginController = require('../http/controllers/auth/login-controller')
const orderController = require('../http/controllers/order-controller')
const stripeController = require('../http/controllers/stripe-controller')
const { verifyTokenAndAuthorization, verifyTokenAndAdmin, verifyToken } = require('../http/middlewares/verifyToken')
const stripe = require('stripe')("sk_test_51Kevl1SFKShQSTPWkzHvtrdkS5Adu40BNHcBlLBOrfrskmpngubCmCNDpqyLrhK0KkfqTGgfXh7ymRgq1MmD11wz00kzpJ0Csp")

const router = express.Router()

router.post('/register', registerController.register)
router.post('/login', loginController.login)
router.put('/:id', verifyTokenAndAuthorization, loginController.update)
router.delete('/:id', verifyTokenAndAuthorization, loginController.DeleteUser)
router.get('/find/:id', verifyTokenAndAdmin, loginController.getUser)
router.get('/find', verifyTokenAndAdmin, loginController.allUser)
router.get('/stats', verifyTokenAndAdmin, loginController.userStats)
router.post('/product', verifyTokenAndAdmin, productController.createProduct)
router.put('/product/:id', verifyTokenAndAdmin, productController.updateProduct)
router.delete('/product/:id', verifyTokenAndAdmin, productController.deleteProduct)
router.get('/product/find/:id', productController.getProduct)
router.get('/product/find', productController.allProduct)
router.post('/cart', verifyToken, cartController.createCart)
router.put('/cart/:id', verifyTokenAndAuthorization, cartController.updateCart)
router.delete('/cart/:id', verifyTokenAndAuthorization, cartController.deleteCart)
router.get('/cart/:id', verifyTokenAndAuthorization, cartController.getCart)
router.get('/cart', verifyTokenAndAdmin, cartController.allCart)
router.post('/order', verifyToken, orderController.createOrder)
router.put('/order/:id', verifyTokenAndAdmin, orderController.updateOrder)
router.delete('/order/:id', verifyTokenAndAdmin, orderController.deleteOrder)
router.get('/order/:id', verifyTokenAndAuthorization, orderController.getOrder)
router.get('/order', verifyTokenAndAdmin, orderController.allOrder)
router.get('/income', verifyTokenAndAdmin, orderController.getIncome)
router.post('/payment', stripeController.payment)
module.exports = router