import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Announcement from '../components/Annoucement'
import Slider from '../components/Slider'
import Categories from '../components/Categories'
import Newsletter from '../components/Newsletter'
import ProductList from '../components/ProductList'
import {useSelector} from 'react-redux'
import {useRouter} from 'next/router'

export default function Home() {
  const router = useRouter()
  const {currentUser} = useSelector(state => state.persistedReducer.user)

  return (
    <div className={styles.container}>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          currentUser?.isAdmin ?
          location.replace('/admin') : 
          <div>
        <Announcement/>
        <Slider/>
        <Categories/>
        <ProductList/>
        <Newsletter/>
        </div>
        }
      </main>
    </div>
  )
}
